name: ✅ CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  lint:
    uses: libhal/libhal/.github/workflows/checks.yml@main
    with:
      library: libhal-esp8266
      coverage: true
    secrets: inherit